inherit_from: .rubocop_todo.yml

Style/ConditionalAssignment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

ClassLength:
  Max: 250
MethodLength:
  Max: 250

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'
