# club_category , club , club_settings , club_period , user , 
# event_category , role , roles_user , system_announcment , announcment
# modellerine seed verisi eklenmiştir.

academic_period = AcademicPeriod.create(name: '2015-2016', is_active: true)

# club_category
club_category = ClubCategory.create([{ name: 'Sosyal Topluluk' }, { name: 'Mesleki Topluluk' }])

# eventCategory
event_category = EventCategory.create([{ name: 'Eğitim' }, { name: 'Festival' }, { name: 'Gezi' }, { name: 'Film-Gösteri-Şölen' }])
event_category = EventCategory.create([{ name: 'Konferans' }, { name: 'Kongre' }, { name: 'Konser-Dinleti' }, { name: 'Çalıştay' }])
event_category = EventCategory.create([{ name: 'Panel' }, { name: 'Seminer' }, { name: 'Sempozyum' }, { name: 'Sergi' }])
event_category = EventCategory.create([{ name: 'Söyleşi' }, { name: 'Kurs' }, { name: 'Yarışma' }, { name: 'Spor' }])
event_category = EventCategory.create([{ name: 'Yardım Kampanyası' }, { name: 'Topluluk Toplantısı' }, { name: 'Anma' }, { name: 'Ödül Töreni' }])

# club
club = Club.create(name: "Siber Güvenlik Topluluğu", short_name: "siber-guvenlik-toplulugu", description: "Topluluk üniversite öğrencilerinde siber güvenlik farkındalığı sağlamak temel amacıdır.", is_active: true, club_category_id: ClubCategory.find_by_name("Sosyal Topluluk").id, creation_date: DateTime.now)

# club-period
club_period = ClubPeriod.create(club_id: club.id, academic_period_id: academic_period.id)

# roller
role_type_advisor = RoleType.create(name: 'Akademik Danışman')
role_type_president = RoleType.create(name: 'Başkan')
role_type_member = RoleType.create(name: 'Üye')
role_type_admin = RoleType.create(name: 'Admin')

# admin kullanıcı
user=User.create(first_name: 'Admin', last_name: "Kullanıcı", user_name: "admin", email: "admin@tbs.com", password: "admin123", is_administrative: true)
rol_admin = Role.create(user_id: user.id, role_type_id: role_type_admin.id)

# announcment
announcment = Announcment.create(club_period_id: club_period.id, title: "Siber g. Duyuru 1", content:"test", is_view: true, is_advisor_confirmation: true)
announcment = Announcment.create(club_period_id: club_period.id, title: "Siber g. Duyuru 2", content:"testtttt", is_view: true, is_advisor_confirmation: false)
announcment = Announcment.create(club_period_id: club_period.id, title: "Siber g. Duyuru 3", content:"testaaaaaa", is_view: false, is_advisor_confirmation: true)

# club-setting
club_setting = ClubSetting.create(club_id: club.id, max_user: 150)

# users
user_advisor = User.create(first_name: "Akademik Danışman", last_name: "Siber G.", user_name: "advisor-siber", email: "advisor-siber@tbs.com", password: "advisor123", is_academic: true, degree: "Prof. Dr.")
user_president = User.create(first_name: "Başkan", last_name: "Siber G.", user_name: "president-siber", email: "president-siber@tbs.com", password: "president123", program_code: "2728")
user_member = User.create(first_name: "Üye", last_name: "Siber G.", user_name: "member-siber", email: "member-siber@tbs.com", password: "member123", program_code: "2728")

# club roles
rol_advisor = Role.create(user_id: user_advisor.id, club_period_id: club_period.id, role_type_id: role_type_advisor.id)
rol_president = Role.create(user_id: user_president.id, club_period_id: club_period.id, role_type_id: role_type_president.id)
rol_member = Role.create(user_id: user_member.id, club_period_id: club_period.id, role_type_id: role_type_member.id)

# club
club = Club.create(name: "Bisiklet Topluluğu", short_name: "bisiklet-toplulugu", description: "Bisikletin önemini ve yaygınlaşmasını amaçlamış bir topluluktur.", is_active: true, club_category_id: ClubCategory.find_by_name("Sosyal Topluluk").id, creation_date: DateTime.now)

# club-period
club_period = ClubPeriod.create(club_id: club.id, academic_period_id: academic_period.id)

# announcments
announcment = Announcment.create(club_period_id: club_period.id, title: "Bisiklet. Duyuru 1", content:"test", is_view: true, is_advisor_confirmation: true)
announcment = Announcment.create(club_period_id: club_period.id, title: "Bisiklet. Duyuru 2", content:"testtttt", is_view: true, is_advisor_confirmation: false)
announcment = Announcment.create(club_period_id: club_period.id, title: "Bisiklet. Duyuru 3", content:"testaaaaaa", is_view: false, is_advisor_confirmation: true)

# club-setting
club_setting = ClubSetting.create(club_id: club.id, max_user: 150)

# users
user_advisor = User.create(first_name: "Akademik Danışman", last_name: "Bisiklet.", user_name: "advisor-bisiklet", email: "advisor-bisiklet@tbs.com", password: "advisor123", is_academic: true, degree: "Prof. Dr.")
user_president = User.create(first_name: "Başkan", last_name: "Bisiklet.", user_name: "president-bisiklet", email: "president-bisiklet@tbs.com", password: "president123", program_code: "2728")
user_member = User.create(first_name: "Üye", last_name: "Bisiklet.", user_name: "member-bisiklet", email: "member-bisiklet@tbs.com", password: "member123", program_code: "2728")

# club roles
rol_advisor = Role.create(user_id: user_advisor.id,club_period_id: club_period.id, role_type_id: role_type_advisor.id)
rol_president = Role.create(user_id: user_president.id,club_period_id: club_period.id, role_type_id: role_type_president.id)
rol_member = Role.create(user_id: user_member.id,club_period_id: club_period.id, role_type_id: role_type_member.id)

# club
club = Club.create(name: "İnşaat Mühendisleri Topluluğu", short_name: "insaat-muhendisligi-toplulugu", description: "İnşaat mühendisliği öğrencilerini geliştirmek temel amacımızdır.", is_active: true, club_category_id: ClubCategory.find_by_name("Mesleki Topluluk").id, creation_date: DateTime.now)

# club-period
club_period = ClubPeriod.create(club_id: club.id, academic_period_id: academic_period.id)

# announcments
announcment = Announcment.create(club_period_id: club_period.id, title: "İnşaat. Duyuru 1", content:"test", is_view: true, is_advisor_confirmation: true)
announcment = Announcment.create(club_period_id: club_period.id, title: "İnşaat. Duyuru 2", content:"testtttt", is_view: true, is_advisor_confirmation: false)
announcment = Announcment.create(club_period_id: club_period.id, title: "İnşaat. Duyuru 3", content:"testaaaaaa", is_view: false, is_advisor_confirmation: true)

# club-setting
club_setting = ClubSetting.create(club_id: club.id, max_user: 150, program_id: "2724")

# users
user_advisor = User.create(first_name: "Akademik Danışman", last_name: "insaat.", user_name: "advisor-insaat", email: "advisor-insaat@tbs.com", password: "advisor123", is_academic: true, degree: "Prof. Dr.")
user_president = User.create(first_name: "Başkan", last_name: "insaat.", user_name: "president-insaat", email: "president-insaat@tbs.com", password: "president123", program_code: "2724")
user_member = User.create(first_name: "Üye", last_name: "insaat.", user_name: "member-insaat", email: "member-insaat@tbs.com", password: "member123", program_code: "2724")

# club roles
rol_advisor = Role.create(user_id: user_advisor.id,club_period_id: club_period.id, role_type_id: role_type_advisor.id)
rol_president = Role.create(user_id: user_president.id,club_period_id: club_period.id, role_type_id: role_type_president.id)
rol_member = Role.create(user_id: user_member.id,club_period_id: club_period.id, role_type_id: role_type_member.id)

# System Announcment 
SystemAnnouncment.create(title: 'Duyuru 1', content: "bu test amaçlı oluşturulmuş bir duyurudur.", is_view: true)
SystemAnnouncment.create(title: 'Duyuru 2', content: "bu test amaçlı oluşturulmuş 2. duyurudur.", is_view: false)
SystemAnnouncment.create(title: 'Duyuru 3', content: "bu test amaçlı oluşturulmuş 3. duyurudur.", is_view: true)
SystemAnnouncment.create(title: 'Duyuru 4', content: "bu test amaçlı oluşturulmuş 4. duyurudur.", is_view: true)
SystemAnnouncment.create(title: 'Duyuru 5', content: "bu test amaçlı oluşturulmuş 5. duyurudur.", is_view: true)

# Event Status
EventStatus.create(status: "SKS Admin Onayı Bekleniyor")
EventStatus.create(status: "SKS Admin Onayladı")
EventStatus.create(status: "SKS Admin Onaylamadı")
EventStatus.create(status: "Akademik Danışman Onayı Bekleniyor")
EventStatus.create(status: "Akademik Danışman Onayladı")
EventStatus.create(status: "Akademik Danışman Onaylamadı")

# New Users
User.create(email: "member1@tbs.com", password: "member123", user_name: "member1", first_name: "member1", last_name: "")
User.create(email: "member2@tbs.com", password: "member123", user_name: "member2", first_name: "member2", last_name: "")
User.create(email: "member3@tbs.com", password: "member123", user_name: "member3", first_name: "member3", last_name: "")
User.create(email: "member4@tbs.com", password: "member123", user_name: "member4", first_name: "member4", last_name: "")
User.create(email: "member5@tbs.com", password: "member123", user_name: "member5", first_name: "member5", last_name: "")
User.create(email: "member6@tbs.com", password: "member123", user_name: "member6", first_name: "member6", last_name: "")
User.create(email: "member7@tbs.com", password: "member123", user_name: "member7", first_name: "member7", last_name: "")
User.create(email: "member8@tbs.com", password: "member123", user_name: "member8", first_name: "member8", last_name: "")
User.create(email: "member9@tbs.com", password: "member123", user_name: "member9", first_name: "member9", last_name: "")
User.create(email: "member10@tbs.com", password: "member123", user_name: "member10", first_name: "member10", last_name: "")
User.create(email: "member11@tbs.com", password: "member123", user_name: "member11", first_name: "member11", last_name: "")
User.create(email: "member12@tbs.com", password: "member123", user_name: "member12", first_name: "member12", last_name: "")
User.create(email: "member13@tbs.com", password: "member123", user_name: "member13", first_name: "member13", last_name: "")
User.create(email: "member14@tbs.com", password: "member123", user_name: "member14", first_name: "member14", last_name: "")
User.create(email: "member15@tbs.com", password: "member123", user_name: "member15", first_name: "member15", last_name: "")
User.create(email: "member16@tbs.com", password: "member123", user_name: "member16", first_name: "member16", last_name: "")
User.create(email: "member17@tbs.com", password: "member123", user_name: "member17", first_name: "member17", last_name: "")
User.create(email: "member18@tbs.com", password: "member123", user_name: "member18", first_name: "member18", last_name: "")
User.create(email: "member19@tbs.com", password: "member123", user_name: "member19", first_name: "member19", last_name: "")
User.create(email: "member20@tbs.com", password: "member123", user_name: "member20", first_name: "member20", last_name: "")
User.create(email: "member21@tbs.com", password: "member123", user_name: "member21", first_name: "member21", last_name: "")
User.create(email: "member22@tbs.com", password: "member123", user_name: "member22", first_name: "member22", last_name: "")
User.create(email: "member23@tbs.com", password: "member123", user_name: "member23", first_name: "member23", last_name: "")
User.create(email: "member24@tbs.com", password: "member123", user_name: "member24", first_name: "member24", last_name: "")
User.create(email: "member25@tbs.com", password: "member123", user_name: "member25", first_name: "member25", last_name: "")
User.create(email: "member26@tbs.com", password: "member123", user_name: "member26", first_name: "member26", last_name: "")
User.create(email: "member27@tbs.com", password: "member123", user_name: "member27", first_name: "member27", last_name: "")
User.create(email: "member28@tbs.com", password: "member123", user_name: "member28", first_name: "member28", last_name: "")
User.create(email: "member29@tbs.com", password: "member123", user_name: "member29", first_name: "member29", last_name: "")
User.create(email: "member30@tbs.com", password: "member123", user_name: "member30", first_name: "member30", last_name: "")
User.create(email: "member31@tbs.com", password: "member123", user_name: "member31", first_name: "member31", last_name: "")
User.create(email: "member32@tbs.com", password: "member123", user_name: "member32", first_name: "member32", last_name: "")
User.create(email: "member33@tbs.com", password: "member123", user_name: "member33", first_name: "member33", last_name: "")
User.create(email: "member34@tbs.com", password: "member123", user_name: "member34", first_name: "member34", last_name: "")
User.create(email: "member35@tbs.com", password: "member123", user_name: "member35", first_name: "member35", last_name: "")
User.create(email: "member36@tbs.com", password: "member123", user_name: "member36", first_name: "member36", last_name: "")
User.create(email: "member37@tbs.com", password: "member123", user_name: "member37", first_name: "member37", last_name: "")
User.create(email: "member38@tbs.com", password: "member123", user_name: "member38", first_name: "member38", last_name: "")
User.create(email: "member39@tbs.com", password: "member123", user_name: "member39", first_name: "member39", last_name: "")
User.create(email: "member40@tbs.com", password: "member123", user_name: "member40", first_name: "member40", last_name: "")
User.create(email: "member41@tbs.com", password: "member123", user_name: "member41", first_name: "member41", last_name: "")
User.create(email: "member42@tbs.com", password: "member123", user_name: "member42", first_name: "member42", last_name: "")
User.create(email: "member43@tbs.com", password: "member123", user_name: "member43", first_name: "member43", last_name: "")
User.create(email: "member44@tbs.com", password: "member123", user_name: "member44", first_name: "member44", last_name: "")
User.create(email: "member45@tbs.com", password: "member123", user_name: "member45", first_name: "member45", last_name: "")
User.create(email: "member46@tbs.com", password: "member123", user_name: "member46", first_name: "member46", last_name: "")
User.create(email: "member47@tbs.com", password: "member123", user_name: "member47", first_name: "member47", last_name: "")
User.create(email: "member48@tbs.com", password: "member123", user_name: "member48", first_name: "member48", last_name: "")
User.create(email: "member49@tbs.com", password: "member123", user_name: "member49", first_name: "member49", last_name: "")
User.create(email: "member50@tbs.com", password: "member123", user_name: "member50", first_name: "member50", last_name: "")
User.create(email: "member51@tbs.com", password: "member123", user_name: "member51", first_name: "member51", last_name: "")
User.create(email: "member52@tbs.com", password: "member123", user_name: "member52", first_name: "member52", last_name: "")
User.create(email: "member53@tbs.com", password: "member123", user_name: "member53", first_name: "member53", last_name: "")
User.create(email: "member54@tbs.com", password: "member123", user_name: "member54", first_name: "member54", last_name: "")
User.create(email: "member55@tbs.com", password: "member123", user_name: "member55", first_name: "member55", last_name: "")
User.create(email: "member56@tbs.com", password: "member123", user_name: "member56", first_name: "member56", last_name: "")
User.create(email: "member57@tbs.com", password: "member123", user_name: "member57", first_name: "member57", last_name: "")
User.create(email: "member58@tbs.com", password: "member123", user_name: "member58", first_name: "member58", last_name: "")
User.create(email: "member59@tbs.com", password: "member123", user_name: "member59", first_name: "member59", last_name: "")
User.create(email: "member60@tbs.com", password: "member123", user_name: "member60", first_name: "member60", last_name: "")
User.create(email: "member61@tbs.com", password: "member123", user_name: "member61", first_name: "member61", last_name: "")
User.create(email: "member62@tbs.com", password: "member123", user_name: "member62", first_name: "member62", last_name: "")
User.create(email: "member63@tbs.com", password: "member123", user_name: "member63", first_name: "member63", last_name: "")
User.create(email: "member64@tbs.com", password: "member123", user_name: "member64", first_name: "member64", last_name: "")
User.create(email: "member65@tbs.com", password: "member123", user_name: "member65", first_name: "member65", last_name: "")
User.create(email: "member66@tbs.com", password: "member123", user_name: "member66", first_name: "member66", last_name: "")
User.create(email: "member67@tbs.com", password: "member123", user_name: "member67", first_name: "member67", last_name: "")
User.create(email: "member68@tbs.com", password: "member123", user_name: "member68", first_name: "member68", last_name: "")
User.create(email: "member69@tbs.com", password: "member123", user_name: "member69", first_name: "member69", last_name: "")
User.create(email: "member70@tbs.com", password: "member123", user_name: "member70", first_name: "member70", last_name: "")
User.create(email: "member71@tbs.com", password: "member123", user_name: "member71", first_name: "member71", last_name: "")
User.create(email: "member72@tbs.com", password: "member123", user_name: "member72", first_name: "member72", last_name: "")
User.create(email: "member73@tbs.com", password: "member123", user_name: "member73", first_name: "member73", last_name: "")
User.create(email: "member74@tbs.com", password: "member123", user_name: "member74", first_name: "member74", last_name: "")
User.create(email: "member75@tbs.com", password: "member123", user_name: "member75", first_name: "member75", last_name: "")
User.create(email: "member76@tbs.com", password: "member123", user_name: "member76", first_name: "member76", last_name: "")
User.create(email: "member77@tbs.com", password: "member123", user_name: "member77", first_name: "member77", last_name: "")
User.create(email: "member78@tbs.com", password: "member123", user_name: "member78", first_name: "member78", last_name: "")
User.create(email: "member79@tbs.com", password: "member123", user_name: "member79", first_name: "member79", last_name: "")
User.create(email: "member80@tbs.com", password: "member123", user_name: "member80", first_name: "member80", last_name: "")
User.create(email: "member81@tbs.com", password: "member123", user_name: "member81", first_name: "member81", last_name: "")
User.create(email: "member82@tbs.com", password: "member123", user_name: "member82", first_name: "member82", last_name: "")
User.create(email: "member83@tbs.com", password: "member123", user_name: "member83", first_name: "member83", last_name: "")
User.create(email: "member84@tbs.com", password: "member123", user_name: "member84", first_name: "member84", last_name: "")
User.create(email: "member85@tbs.com", password: "member123", user_name: "member85", first_name: "member85", last_name: "")
User.create(email: "member86@tbs.com", password: "member123", user_name: "member86", first_name: "member86", last_name: "")
User.create(email: "member87@tbs.com", password: "member123", user_name: "member87", first_name: "member87", last_name: "")
User.create(email: "member88@tbs.com", password: "member123", user_name: "member88", first_name: "member88", last_name: "")
User.create(email: "member89@tbs.com", password: "member123", user_name: "member89", first_name: "member89", last_name: "")
User.create(email: "member90@tbs.com", password: "member123", user_name: "member90", first_name: "member90", last_name: "")
User.create(email: "member91@tbs.com", password: "member123", user_name: "member91", first_name: "member91", last_name: "")
User.create(email: "member92@tbs.com", password: "member123", user_name: "member92", first_name: "member92", last_name: "")
User.create(email: "member93@tbs.com", password: "member123", user_name: "member93", first_name: "member93", last_name: "")
User.create(email: "member94@tbs.com", password: "member123", user_name: "member94", first_name: "member94", last_name: "")
User.create(email: "member95@tbs.com", password: "member123", user_name: "member95", first_name: "member95", last_name: "")
User.create(email: "member96@tbs.com", password: "member123", user_name: "member96", first_name: "member96", last_name: "")
User.create(email: "member97@tbs.com", password: "member123", user_name: "member97", first_name: "member97", last_name: "")
User.create(email: "member98@tbs.com", password: "member123", user_name: "member98", first_name: "member98", last_name: "")
User.create(email: "member99@tbs.com", password: "member123", user_name: "member99", first_name: "member99", last_name: "")
User.create(email: "member100@tbs.com", password: "member123", user_name: "member100", first_name: "member100", last_name: "")
User.create(email: "member101@tbs.com", password: "member123", user_name: "member101", first_name: "member101", last_name: "")
User.create(email: "member102@tbs.com", password: "member123", user_name: "member102", first_name: "member102", last_name: "")
User.create(email: "member103@tbs.com", password: "member123", user_name: "member103", first_name: "member103", last_name: "")
User.create(email: "member104@tbs.com", password: "member123", user_name: "member104", first_name: "member104", last_name: "")
User.create(email: "member105@tbs.com", password: "member123", user_name: "member105", first_name: "member105", last_name: "")
User.create(email: "member106@tbs.com", password: "member123", user_name: "member106", first_name: "member106", last_name: "")
User.create(email: "member107@tbs.com", password: "member123", user_name: "member107", first_name: "member107", last_name: "")
User.create(email: "member108@tbs.com", password: "member123", user_name: "member108", first_name: "member108", last_name: "")
User.create(email: "member109@tbs.com", password: "member123", user_name: "member109", first_name: "member109", last_name: "")
User.create(email: "member110@tbs.com", password: "member123", user_name: "member110", first_name: "member110", last_name: "")
User.create(email: "member111@tbs.com", password: "member123", user_name: "member111", first_name: "member111", last_name: "")
User.create(email: "member112@tbs.com", password: "member123", user_name: "member112", first_name: "member112", last_name: "")
User.create(email: "member113@tbs.com", password: "member123", user_name: "member113", first_name: "member113", last_name: "")
User.create(email: "member114@tbs.com", password: "member123", user_name: "member114", first_name: "member114", last_name: "")
User.create(email: "member115@tbs.com", password: "member123", user_name: "member115", first_name: "member115", last_name: "")
User.create(email: "member116@tbs.com", password: "member123", user_name: "member116", first_name: "member116", last_name: "")
User.create(email: "member117@tbs.com", password: "member123", user_name: "member117", first_name: "member117", last_name: "")
User.create(email: "member118@tbs.com", password: "member123", user_name: "member118", first_name: "member118", last_name: "")
User.create(email: "member119@tbs.com", password: "member123", user_name: "member119", first_name: "member119", last_name: "")
User.create(email: "member120@tbs.com", password: "member123", user_name: "member120", first_name: "member120", last_name: "")
User.create(email: "member121@tbs.com", password: "member123", user_name: "member121", first_name: "member121", last_name: "")
User.create(email: "member122@tbs.com", password: "member123", user_name: "member122", first_name: "member122", last_name: "")
User.create(email: "member123@tbs.com", password: "member123", user_name: "member123", first_name: "member123", last_name: "")
User.create(email: "member124@tbs.com", password: "member123", user_name: "member124", first_name: "member124", last_name: "")
User.create(email: "member125@tbs.com", password: "member123", user_name: "member125", first_name: "member125", last_name: "")
User.create(email: "member126@tbs.com", password: "member123", user_name: "member126", first_name: "member126", last_name: "")
User.create(email: "member127@tbs.com", password: "member123", user_name: "member127", first_name: "member127", last_name: "")
User.create(email: "member128@tbs.com", password: "member123", user_name: "member128", first_name: "member128", last_name: "")
User.create(email: "member129@tbs.com", password: "member123", user_name: "member129", first_name: "member129", last_name: "")
User.create(email: "member130@tbs.com", password: "member123", user_name: "member130", first_name: "member130", last_name: "")
User.create(email: "member131@tbs.com", password: "member123", user_name: "member131", first_name: "member131", last_name: "")
User.create(email: "member132@tbs.com", password: "member123", user_name: "member132", first_name: "member132", last_name: "")
User.create(email: "member133@tbs.com", password: "member123", user_name: "member133", first_name: "member133", last_name: "")
User.create(email: "member134@tbs.com", password: "member123", user_name: "member134", first_name: "member134", last_name: "")
User.create(email: "member135@tbs.com", password: "member123", user_name: "member135", first_name: "member135", last_name: "")
User.create(email: "member136@tbs.com", password: "member123", user_name: "member136", first_name: "member136", last_name: "")
User.create(email: "member137@tbs.com", password: "member123", user_name: "member137", first_name: "member137", last_name: "")
User.create(email: "member138@tbs.com", password: "member123", user_name: "member138", first_name: "member138", last_name: "")
User.create(email: "member139@tbs.com", password: "member123", user_name: "member139", first_name: "member139", last_name: "")
User.create(email: "member140@tbs.com", password: "member123", user_name: "member140", first_name: "member140", last_name: "")
User.create(email: "member141@tbs.com", password: "member123", user_name: "member141", first_name: "member141", last_name: "")
User.create(email: "member142@tbs.com", password: "member123", user_name: "member142", first_name: "member142", last_name: "")
User.create(email: "member143@tbs.com", password: "member123", user_name: "member143", first_name: "member143", last_name: "")
User.create(email: "member144@tbs.com", password: "member123", user_name: "member144", first_name: "member144", last_name: "")
User.create(email: "member145@tbs.com", password: "member123", user_name: "member145", first_name: "member145", last_name: "")
User.create(email: "member146@tbs.com", password: "member123", user_name: "member146", first_name: "member146", last_name: "")
User.create(email: "member147@tbs.com", password: "member123", user_name: "member147", first_name: "member147", last_name: "")
User.create(email: "member148@tbs.com", password: "member123", user_name: "member148", first_name: "member148", last_name: "")
User.create(email: "member149@tbs.com", password: "member123", user_name: "member149", first_name: "member149", last_name: "")
User.create(email: "member150@tbs.com", password: "member123", user_name: "member150", first_name: "member150", last_name: "")
User.create(email: "member151@tbs.com", password: "member123", user_name: "member151", first_name: "member151", last_name: "")
User.create(email: "member152@tbs.com", password: "member123", user_name: "member152", first_name: "member152", last_name: "")
User.create(email: "member153@tbs.com", password: "member123", user_name: "member153", first_name: "member153", last_name: "")
User.create(email: "member154@tbs.com", password: "member123", user_name: "member154", first_name: "member154", last_name: "")
User.create(email: "member155@tbs.com", password: "member123", user_name: "member155", first_name: "member155", last_name: "")
User.create(email: "member156@tbs.com", password: "member123", user_name: "member156", first_name: "member156", last_name: "")
User.create(email: "member157@tbs.com", password: "member123", user_name: "member157", first_name: "member157", last_name: "")
User.create(email: "member158@tbs.com", password: "member123", user_name: "member158", first_name: "member158", last_name: "")
User.create(email: "member159@tbs.com", password: "member123", user_name: "member159", first_name: "member159", last_name: "")
User.create(email: "member160@tbs.com", password: "member123", user_name: "member160", first_name: "member160", last_name: "")
User.create(email: "member161@tbs.com", password: "member123", user_name: "member161", first_name: "member161", last_name: "")
User.create(email: "member162@tbs.com", password: "member123", user_name: "member162", first_name: "member162", last_name: "")
User.create(email: "member163@tbs.com", password: "member123", user_name: "member163", first_name: "member163", last_name: "")
User.create(email: "member164@tbs.com", password: "member123", user_name: "member164", first_name: "member164", last_name: "")
User.create(email: "member165@tbs.com", password: "member123", user_name: "member165", first_name: "member165", last_name: "")
User.create(email: "member166@tbs.com", password: "member123", user_name: "member166", first_name: "member166", last_name: "")
User.create(email: "member167@tbs.com", password: "member123", user_name: "member167", first_name: "member167", last_name: "")
User.create(email: "member168@tbs.com", password: "member123", user_name: "member168", first_name: "member168", last_name: "")
User.create(email: "member169@tbs.com", password: "member123", user_name: "member169", first_name: "member169", last_name: "")
User.create(email: "member170@tbs.com", password: "member123", user_name: "member170", first_name: "member170", last_name: "")
User.create(email: "member171@tbs.com", password: "member123", user_name: "member171", first_name: "member171", last_name: "")
User.create(email: "member172@tbs.com", password: "member123", user_name: "member172", first_name: "member172", last_name: "")
User.create(email: "member173@tbs.com", password: "member123", user_name: "member173", first_name: "member173", last_name: "")
User.create(email: "member174@tbs.com", password: "member123", user_name: "member174", first_name: "member174", last_name: "")
User.create(email: "member175@tbs.com", password: "member123", user_name: "member175", first_name: "member175", last_name: "")
User.create(email: "member176@tbs.com", password: "member123", user_name: "member176", first_name: "member176", last_name: "")
User.create(email: "member177@tbs.com", password: "member123", user_name: "member177", first_name: "member177", last_name: "")
User.create(email: "member178@tbs.com", password: "member123", user_name: "member178", first_name: "member178", last_name: "")
User.create(email: "member179@tbs.com", password: "member123", user_name: "member179", first_name: "member179", last_name: "")
User.create(email: "member180@tbs.com", password: "member123", user_name: "member180", first_name: "member180", last_name: "")
User.create(email: "member181@tbs.com", password: "member123", user_name: "member181", first_name: "member181", last_name: "")
User.create(email: "member182@tbs.com", password: "member123", user_name: "member182", first_name: "member182", last_name: "")
User.create(email: "member183@tbs.com", password: "member123", user_name: "member183", first_name: "member183", last_name: "")
User.create(email: "member184@tbs.com", password: "member123", user_name: "member184", first_name: "member184", last_name: "")
User.create(email: "member185@tbs.com", password: "member123", user_name: "member185", first_name: "member185", last_name: "")
User.create(email: "member186@tbs.com", password: "member123", user_name: "member186", first_name: "member186", last_name: "")
User.create(email: "member187@tbs.com", password: "member123", user_name: "member187", first_name: "member187", last_name: "")
User.create(email: "member188@tbs.com", password: "member123", user_name: "member188", first_name: "member188", last_name: "")
User.create(email: "member189@tbs.com", password: "member123", user_name: "member189", first_name: "member189", last_name: "")
User.create(email: "member190@tbs.com", password: "member123", user_name: "member190", first_name: "member190", last_name: "")
User.create(email: "member191@tbs.com", password: "member123", user_name: "member191", first_name: "member191", last_name: "")
User.create(email: "member192@tbs.com", password: "member123", user_name: "member192", first_name: "member192", last_name: "")
User.create(email: "member193@tbs.com", password: "member123", user_name: "member193", first_name: "member193", last_name: "")
User.create(email: "member194@tbs.com", password: "member123", user_name: "member194", first_name: "member194", last_name: "")
User.create(email: "member195@tbs.com", password: "member123", user_name: "member195", first_name: "member195", last_name: "")
User.create(email: "member196@tbs.com", password: "member123", user_name: "member196", first_name: "member196", last_name: "")
User.create(email: "member197@tbs.com", password: "member123", user_name: "member197", first_name: "member197", last_name: "")
User.create(email: "member198@tbs.com", password: "member123", user_name: "member198", first_name: "member198", last_name: "")
User.create(email: "member199@tbs.com", password: "member123", user_name: "member199", first_name: "member199", last_name: "")
User.create(email: "member200@tbs.com", password: "member123", user_name: "member200", first_name: "member200", last_name: "")
